---
title: "Functions presentation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Functions_presentation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ermeeth)
library(dplyr)
library(ggplot2)
library(tidyr)
library(ofce)
library(stringr)
library(flextable)
library(officer)
library(colorspace)
```

```{r dataload}
data <- oilprice_fra
scenario_name <- "oilprice_fra"
template_default <-  "ofce"
start_year = 2020
end_year = 2050
source("../inst/bridge_c28_s32.R")
source("../tests/codenames_c28_s32.R")
```

# Plot functions

## Simple plots 
```{r Simple Plot}
label_macro <- c("Gross domestic Production", "Households consumption", "Investment", "Public spendings")
simpleplot(data,c("GDP", "CH", "I", "G"), label_macro, startyear =  start_year,endyear =  end_year, titleplot = "GDP and its components  (in difference from baseline)")

simpleplot(data,c("RDEBT_G_VAL"),label_series = "Public Debt", startyear = start_year, endyear = 2030, "diff", titleplot = "Public Account (in GDP points, difference from baseline)" , percent_label  = FALSE)

simpleplot(data,c("RDEBT_G_VAL"),label_series = "Public Debt", startyear = start_year, endyear = 2050, "diff", titleplot = "Public Account (in GDP points, difference from baseline)" , percent_label  = FALSE)
simpleplot(data,c("RDEBT_G_VAL"),label_series = "Public Debt", startyear = start_year, endyear = 2050, "diff", titleplot = "Public Account (in GDP points, difference from baseline)" , percent_label  = FALSE,custom_x_breaks = 3)
simpleplot(data,c("RDEBT_G_VAL"),label_series = "Public Debt", startyear = start_year, endyear = 2050, "diff", titleplot = "Public Account (in GDP points, difference from baseline)" , percent_label  = FALSE,custom_x_breaks = "R")
```


## Contrib plot

### General contrib plot

```{r contrib plot}
GDP_comp <- c( "CH","X","M", "I", "G")
GDP_comp_label <- c( "Households consumption","Exports","Imports", "Investment", "Public spending")


# Between two selected scenarios, contributions to yearly growth rate difference (in pp)
data_plot <-  contrib(data,"GDP", GDP_comp, scenar = c("baseline",scenario_name))
contrib.plot(data_plot, series = GDP_comp, 
             label_series = GDP_comp_label,
             startyear = 2020,
             titleplot = "Contributions to GDP growth (in relative deviation from baseline)")

# For a selected scenario, contributions to yearly growth rate (in pp)
data_plot <-  contrib(data,"GDP", GDP_comp, scenar = c(scenario_name, "baseline"), indicator = "gr.diff")

contrib.plot(data_plot, series = GDP_comp, 
             label_series = GDP_comp_label,
             line_tot = TRUE,
             startyear = 2020,
             titleplot = "Contributions to GDP growth deviation (in difference in pp from baseline)")

# For a selected scenario, contributions to yearly growth rate (in pp)
data_plot <-  contrib(data,"GDP", GDP_comp, scenar = c( "oilprice_fra"), indicator = "gr.diff")

contrib.plot(data_plot, series = GDP_comp, 
             label_series = GDP_comp_label,
             line_tot = TRUE,
             startyear = 2020,
             titleplot = "Contributions to GDP growth rate (in pp)")

```

### Sector contrib plots
```{r sector contrib}
data_plot <- contrib.sub(data,var1 =  "Y",
                         group_type = "sector", scenar = c("baseline", scenario_name))

contrib.sub.plot(data_plot, template = "ofce", startyear = 2020, endyear = 2050, line_tot =  TRUE, titleplot = "Total production and sectorial decomposition  (in difference from baseline)")


```

## Sector plots

### sector bar plots

```{r sector bar plots}
data_CO2 <- data %>% filter(year %in% (start_year:end_year)) %>% filter(grepl("^EMS_.+_CO2_S.*$",variable)) %>% 
  mutate(variable = str_remove(variable,"_(CI|MAT|Y)")) %>% 
  group_by(year,sector,variable) %>% 
  summarise_at(all_of(c("baseline",scenario_name)), sum) %>% ungroup()


stacked_sc_plot(data_CO2,"EMS_CO2",interval = 5, diff = TRUE, title = "CO2 emissions by sector (in difference from baseline)")

stacked_sc_plot(data,"Y",interval = 5, diff = TRUE, title = "CO2 emissions by sector (in difference from baseline)",bridge4palette_sectors = bridge_sectors)
```

### Sector curve plots

```{r curve sector plots}
curve_sc_plot(data,"Y", growth.rate = FALSE,diff = TRUE,abs.diff = FALSE,startyear = start_year,endyear = 2030, title = "Production by sector (in difference from baseline)")

```


