###Commodities
names_commodities <- rbind(
c('Products of agriculture, Hunting, and Fishing','cagr'),
c('Products of Forestry ','cfor'),
c('Food products and beverages','cfoo'),
c('Motor vehicles, trailers and semi-trailers','cveh'),
c('Non-metallic minerals','cgla'),
c('Paper and paperboard','cpap'),
c('Chemicals','cche'),
c('Plastics products','cpla'),
c('Metals','cmet'),
c('Other goods for industry','cigo'),
c('Other goods for consumers','ccgo'),
c('Construction and construction works','ccon'),
c('Rail transport','crai'),
c('Road transport','croa'),
c('Water transport','cwat'),
c('Air transport','cair'),
c('Business services','cpri'),
c('Financial services','cfin'),
c('Public services','cpub'),
c('Non-energy mining','cmin'),
c('Coal and coal products','ccoa'),
c('Crude oil','ccoi'),
c('Oil-derived fuels','cfut'),
c('Natural gas','cgas'),
c('Electricity','cele')) %>% 
  as.data.frame() %>% rename(name = V1,code = V2)

names_sectors <- rbind(
c('Agriculture and fishing','sagr'),
c('Forestry','sfor'),
c('Manufacture of food products and beverages','sfoo'),
c('Manufacture of motor vehicles, trailers and semi-trailers','sveh'),
c('Manufacture of non-metallic mineral products','sgla'),
c('Manufacture of paper and paperboard','spap'),
c('Manufacture of chemicals','sche'),
c('Manufacture of plastics products','spla'),
c('Metallurgy and other goods for industry','sigo'),
c('Manufacture of other goods for consumers','scgo'),
c('Construction of buildings and Civil engineering','scon'),
c('Rail transport','srai'),
c('Road transport','sroa'),
c('Water transport','swat'),
c('Air transport','sair'),
c('Business services','spri'),
c('Financial services','sfin'),
c('Public services','spub'),
c('Mining','smin'),
c('Production of refined oil','soil'),
c('Production of natural gas','sgas'),
c('Nuclear electricity generation','senu'),
c('Oil-fired electricity generation','seoi'),
c('Gas-fired electricity generation','sega'),
c('Coal-fired electricity generation','seco'),
c('Wind electricity generation','sewi'),
c('Solar electricity generation','seso'),
c('Hydroelectric electricity generation','sehy'),
c('Electricity - Others','seot')) %>% 
  as.data.frame() %>% rename(name = V1,code = V2)


