#' selectseries extract series from a long form data.frame and apply a transformation
#'
#' @param data a long form ThreeMe data.frame generated by loadResults.
#' @param scenarios the name of the scenario (must match the name of scenario column in the data.frame). Length : 1
#' @param series the series to select and transform
#' @param startyear First year of the sample to extract. If NULL (default) the earliest year available will be used.
#' @param endyear Last year of the sample to extract. If NULL (default) the lastest year available will be used.
#' @param transformation The transformation to apply. The options are : "reldiff" (default) for relative difference with the baseline, "diff" for the absolute difference with the baseline. Anything else will plot levels
#' @import dplyr
#'
#' @return a long form data.frame with only the selected series and years and new columns with some calculations over the scenarios.
#' @export
#'
selectseries <- function(data,
                         scenarios,
                         series,
                         startyear = NULL,
                         endyear = NULL,
                         transformation="reldiff") {

  # To debug the function step by step, activate line below
  #browser()

  if (is.null(startyear)){startyear  =  min(data$year)}
  if (is.null(endyear)){endyear  =  max(data$year)}
  if (length(scenarios) > 0 ){stop(message = "Only one scenario must be specified.")}

  selection <- data %>%

    # Filter relevant data: see https://dplyr.tidyverse.org/reference/filter.html
    dplyr::filter(variable %in% series) %>%


    ## Calculation per variable
    group_by(variable) %>%
    mutate(lag_baseline = dplyr::lag(baseline),
           lag_scenario = dplyr::lag(get(scenarios)),
           mean_baseline = mean(baseline),
           index_baseline = baseline/baseline[which(year ==  startyear)]) %>%
    ungroup() %>%

    ## Calculation for the all database (all variables)
    mutate(transformation = transformation,
           transfo = ifelse(transformation == "reldiff", (get(scenarios)/baseline-1),
                            ifelse(transformation == "diff", (get(scenarios) - baseline),
                                   (get(scenarios) - baseline))),
           gr_base =  (baseline/lag_baseline-1),
           gr_scen =  (get(scenarios)/lag_scenario-1),
           base =  baseline,
           scen =  get(scenarios)
    ) %>%

    as.data.frame() %>% select(-transformation)  %>%

    dplyr::filter(year %in% (startyear:endyear))




}
